import type { NextPage } from 'next'
import Head from 'next/head'
import ImageBoard from '../components/Home/ImageBoard'
import CardHolder from '../components/Home/Card/CardHolder'
import HomeAbout from '../components/Home/HomeAbout'
import MessageFromPrincipal from '../components/Home/MessageFromPrincipal'
import News from '../components/Home/News'
import Statistic from '../components/Home/Statistic/Statistic'
import CourseHolder from '../components/Home/Courses/CourseHolder'
import Events from '../components/Home/Events/Events'

import Quote from '../components/Home/Quote'
import Memories from '../components/Home/Memories/Memories'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageBoard />
      <CardHolder />
      <HomeAbout />
      <div className='grid lg:grid-cols-3 gaps-4 py-10 px-16 space-y-10'>
        <MessageFromPrincipal />
        <News />
      </div>
      <Statistic />
      <CourseHolder />
      <Events />
      <br />
      <Quote />
      <br />
      <Memories />
      <br />
    </div>
  )
}

export default Home
